#!/usr/bin/expect
set host [lindex $argv 0];
set password "$env(CVM_PASSWORD)"

eval spawn ssh -oStrictHostKeyChecking=no -oCheckHostIP=no admin@$host

# Use the correct prompt
set prompt ": $"
interact -o -nobuffer -re $prompt return
send "Nutanix/4u\r"
interact -o -nobuffer -re $prompt return
send "Nutanix/4u\r"
interact -o -nobuffer -re $prompt return
send "$password\r"
interact -o -nobuffer -re $prompt return
send "$password\r"
interact
